package com.example.demo.algorithm.ztl.model;

import com.example.demo.algorithm.ztl.model.base.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News().dao();
}
