package com.example.demo.algorithm.ztl.model;

import com.example.demo.algorithm.ztl.model.base.BaseNewslogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newslogs extends BaseNewslogs<Newslogs> {
	public static final Newslogs dao = new Newslogs().dao();
}
