package com.example.demo.algorithm.ztl.model;

import com.example.demo.algorithm.ztl.model.base.BaseNewsmodules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newsmodules extends BaseNewsmodules<Newsmodules> {
	public static final Newsmodules dao = new Newsmodules().dao();
}
