package com.example.demo.algorithm.ztl.model;

import com.example.demo.algorithm.ztl.model.base.BaseRecommendations;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recommendations extends BaseRecommendations<Recommendations> {
	public static final Recommendations dao = new Recommendations().dao();
}
