mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    com.example.demo.controller: debug
  file:
    path: log/dailyLog
spring:
  thymeleaf:
    cache: false
  datasource:
    username: news
    password: news
    url: jdbc:mysql://121.4.33.213:3306/news?serverTimeZone=UTC&useUnicode=true&characterUnicoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: gengxuelong_pool
      minimum-idle: 5
      idle-timeout: 1800000
      auto-commit: true

      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 121.4.33.213
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: 10000ms
        max-idle: 200
        min-idle: 10
server:
  port: 8080