package com.example.demo.algorithm.ztl.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewslogs<M extends BaseNewslogs<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setUserId(Long userId) {
		set("user_id", userId);
	}

	public Long getUserId() {
		return getLong("user_id");
	}

	public void setNewsId(Long newsId) {
		set("news_id", newsId);
	}

	public Long getNewsId() {
		return getLong("news_id");
	}

	public void setViewTime(java.util.Date viewTime) {
		set("view_time", viewTime);
	}

	public java.util.Date getViewTime() {
		return getDate("view_time");
	}

	public void setPreferDegree(Integer preferDegree) {
		set("prefer_degree", preferDegree);
	}

	public Integer getPreferDegree() {
		return getInt("prefer_degree");
	}
	
}

