package com.example.demo.algorithm.ztl.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return getStr("content");
	}

	public void setNewsTime(java.util.Date newsTime) {
		set("news_time", newsTime);
	}

	public java.util.Date getNewsTime() {
		return getDate("news_time");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return getStr("title");
	}

	public void setModuleId(Integer moduleId) {
		set("module_id", moduleId);
	}

	public Integer getModuleId() {
		return getInt("module_id");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return getStr("url");
	}
	
}

